flaskblog/main/routes.py
from flask import render_template, url_for, redirect, request, session, Blueprint
from flaskblog import db
import re


main = Blueprint('main', __name__)

@main.route('/')
@main.route('/home', methods=['GET', 'POST'])
def home():
	errors = {}
	values = {}
	if 'loggedin' in session:
		if request.method == 'POST':
			idUser = request.form['idUser']
			title = request.form['title']
			content = request.form['content']
			if re.match(r'^[a-zA-Z0-9\+\:\@\#\$\%\&\*\{\}\]\/\.\-\_\,\(\)\?\!\"\s]+$', request.form['title']):
				values['title'] = request.form['title']
			elif len(title) == 0:
				errors['title'] = "Va rugam completati campul 'Title'."
			else:
				errors['title'] = "Campul 'Title' contine caractere interzise."
			if re.match(r'^[a-zA-Z0-9\+\:\@\#\$\%\&\*\{\}\]\/\.\-\_\,\(\)\?\!\"\s]+$', request.form['content']):
				values['content'] = request.form['content']
			elif len(content) == 0:
				errors['content'] = "Va rugam completati campul 'Content'."
			else:
				errors['content'] = "Campul 'Content' contine caractere interzise."
			if len(errors) == 0:
				db.insert("INSERT INTO posts (idUser, title, content) VALUES ('{0}', '{1}', '{2}')".format(idUser, values['title'], values['content']))
				return redirect (url_for('postings.posts'))
		return render_template('home.html', username = session['username'], idUser = session['id'], errors = errors, form = request.form if request.method == 'POST' else None)
	return redirect(url_for('users.login'))

			

flaskblog/posts/routes.py
from flask import render_template, url_for, redirect, request, session, Blueprint, abort
from flaskblog import db
import re, math, base64, json
from urllib.parse import urlparse

postings = Blueprint('postings', __name__)

def checker( function ):
	def wrapper( **kwargs ):
		if 'loggedin' not in session:
			return redirect( url_for( 'users.login' ) )
		return function( **kwargs )

	wrapper.__name__ = function.__name__
	return wrapper


@checker
@postings.route('/posts', defaults = {'page': 1}, methods=['GET', 'POST'])
@postings.route('/posts/page/<int:page>')
def posts(page):
	o = urlparse(request.base_url)
	db.query("""SET session sql_mode='NO_ENGINE_SUBSTITUTION'""")
	limit = 3
	offset = page*limit - limit
	next = page+1
	prev = page-1
	post_IDS = []
	count = db.select(""" SELECT count(*) AS count FROM posts """)
	count = count['count']
	pages = math.ceil(count / limit)
	post_details = db.select( """
								SELECT * 
								FROM posts 
								LEFT JOIN users ON users.idUser = posts.idUser 
								WHERE statusPost = 1 
								AND statusUser = 1 
								ORDER BY posts.datePosted DESC LIMIT {0} OFFSET {1}
								""".format(limit, offset), False )
	for post in post_details:
		post_IDS.append( str( post['idPost'] ) )
		
	comments = db.select( """
							SELECT * 
							FROM comments 
							LEFT JOIN users ON users.idUser = comments.idUser
							WHERE statusComment = 1  
							AND statusUser = 1
							AND idPost IN ( {0} )
							ORDER BY comments.dateComment DESC
							""".format( ", ".join( post_IDS ) ), False )
	
	commentsAdded = {}
	if post_details:
		for post in post_details:
			commentsAdded[post['idPost']] = []
		if comments:
			for comment in comments:
				commentsAdded[comment['idPost']].append(comment)
	return render_template('posts.html', post_details = post_details, username = session['username'], commentsAdded = commentsAdded, next = next, prev = prev, pages = pages, pageNumber = page )
	
@checker		
@postings.route('/edit-comment/<int:idComment>', methods=['GET', 'POST'])
def edit_comment(idComment):
	data = {}
	if not str( idComment ).isdigit():
		return redirect( url_for( 'postings.posts' ) )
	if not 'loggedin' in session:
		return redirect( url_for( 'users.login' ) )
	context = db.select( """
							SELECT context FROM comments WHERE idComment='{0}' AND statusComment=1
						 """.format( idComment ) )
	if not context or not context['context']:
		return redirect( url_for( 'postings.posts' ) )
	data['context']   = context['context']
	data['idComment'] = idComment

	return render_template( 'edit_comment.html', data=data )

@checker
@postings.route('/delete/<id_post>', methods=['POST'])
def delete(id_post):
	if id_post is None or not isinstance( id_post, str ): 
		return base64.b64encode( json.dumps( { "error": 2, "message": "A avut loc o eroare, va rugam incercati din nou !" } ).encode('utf8') )

	db.delete(f'DELETE FROM posts WHERE idPost = {id_post} AND statusPost = 1')
	return base64.b64encode( json.dumps( { "error":0, "message":"Datele postului au fost modificate cu succes !" } ).encode('utf8') )

@checker
@postings.route('/update/<id_post>', methods=['GET', 'POST'])
def update(id_post):
	errors = {}
	values = {}
	if request.method == "POST":
		title = request.form['title']
		content = request.form['content']
		if not id_post or not id_post.isdigit():
			return abort(404)
		user = db.select("SELECT idUser FROM posts WHERE statusPost = 1 AND idPost = {0}".format(id_post))
		if user and user['idUser'] is not None:
			if session['id'] != user['idUser']:
				return abort(404)
		if re.match(r'^[a-zA-Z0-9\+\:\@\#\$\%\&\*\{\}\]\/\.\-\_\,\(\)\?\!\"\s]+$', request.form['title']):
				values['title'] = request.form['title']
		elif len(title) == 0:
			errors['title'] = "Va rugam completati campul 'Title'."
		else:
			errors['title'] = "Campul 'Title' contine caractere interzise."
		if re.match(r'^[a-zA-Z0-9\+\:\@\#\$\%\&\*\{\}\]\/\.\-\_\,\(\)\?\!\"\s]+$', request.form['content']):
			values['content'] = request.form['content']
		elif len(content) == 0:
			errors['content'] = "Va rugam completati campul 'Content'."
		else:
			errors['content'] = "Campul 'Content' contine caractere interzise."
		if len(errors) == 0:		
			db.update( "UPDATE posts INNER JOIN users ON posts.idUser = users.idUser SET title = '{0}', content = '{1}' WHERE idPost = '{2}' AND statusPost = 1".format(values['title'], values['content'], id_post) )
			return redirect( url_for('postings.posts') )
	post = db.select( "SELECT * FROM posts WHERE idPost = '{0}'".format(id_post) )
	return render_template( 'update.html', post = post, errors = errors)
	 
@checker
@postings.route('/add-comment', methods = [ 'POST' ] )
def comments():

	errors = {}
	values = {}
	data = json.loads( request.get_data().decode('utf-8') )
	
	if not data:
		return base64.b64encode( json.dumps( { "error":2, "errors": "O eroare a avut loc in zona postarilor trimise." } ) )

	if 'context' in data:
		if re.match( '^[a-zA-Z0-9\s@#?!$*%.,()\[\]\{\}" *"]+$', data['context'] ):
			values['context'] = data['context'].strip()
		else:
			errors['context'] = "Campul 'Comments' contine caractere interzise."
	if data['context'] == "":
		errors['context'] = "Campul 'Comments' nu a fost completat. Va rugam sa introduceti date in acest camp."
	
	if 'idPost' in data:
		if re.match( '^[0-9]+$', data['idPost'] ):
			values['idPost'] = data['idPost']
		else:
			errors['idPost'] = "O eroare a avut loc in zona datelor trimise."
	else:
		errors['idPost'] = "O eroare a avut loc in zona datelor trimise."
	
	if len( errors.keys() ) > 0:
		return base64.b64encode( json.dumps( { "error":2, "fields" : errors } ).encode('utf8') )

	db.insert("INSERT INTO comments (idPost, idUser, context) VALUES ('{0}', '{1}', '{2}')".format( values['idPost'], session['id'], values['context'] ))
	return base64.b64encode( json.dumps( { "error":0, "message":"Datele au fost salvate cu success." } ).encode('utf8') )

@checker
@postings.route('/deleteComments/<id_post>', methods=['POST'])
def deleteComments( id_post ):
	if id_post is None or not isinstance( id_post, str ): 
		return base64.b64encode( json.dumps( { "error": 2, "message": "O eroare a avut loc in zona de date necesare!" } ).encode('utf8') )

	db.delete(f'DELETE FROM comments WHERE idComment = {id_post} AND statusComment = 1')
	return base64.b64encode( json.dumps( { "error":0, "message":"Datele au fost modificate cu success!" } ).encode('utf8') )
		

flaskblog/users/routes.py
from flask import render_template, url_for, redirect, request, session, Blueprint
from flaskblog import db, bcrypt
import re

users = Blueprint('users', __name__)


@users.route('/login', methods=['GET', 'POST'])
def login():
	msg = ''
	if 'loggedin' in session:
		return redirect(url_for('main.home'))
	if request.method == 'POST' and 'username' in request.form and 'password' in request.form:
		username = request.form['username']
		password = request.form['password']
		# cur = db.connection.cursor(MySQLdb.cursors.DictCursor)
		account = db.select("SELECT * FROM users WHERE username = '{0}'".format(username))
		# account = cur.fetchone()
		# cur.close()
		if account:
			if bcrypt.check_password_hash(account['password'], password):
				session['loggedin'] = True
				session['id'] = account['idUser']
				session['username'] = account['username']
				return redirect(url_for('main.home'))
			else:
				msg = 'An error has occured !'
		else:
			msg = 'Incorrect username/password!'
	return render_template('index.html', msg=msg)


@users.route('/logout')
def logout():
	session.pop('loggedin', None)
	session.pop('id', None)
	session.pop('username', None)
	return redirect(url_for('users.login'))
   

@users.route('/register', methods=['GET', 'POST'])
def register():
	msg = ''
	if 'loggedin' in session:
		return redirect(url_for('main.home'))
	if request.method == 'POST' and 'username' in request.form and 'email' in request.form and 'password' in request.form:
		username = request.form['username']
		email = request.form['email']
		password = bcrypt.generate_password_hash(request.form['password']).decode('utf-8')
		# cursor = db.connection.cursor(MySQLdb.cursors.DictCursor)
		account = db.select("SELECT * FROM users WHERE username = '{0}'".format(username))
		# account = cursor.fetchone()
		if account:
			msg = 'Account already exists!'
		elif not re.match(r'[^@]+@[^@]+\.[^@]+', email):
			msg = 'Invalid email address!'
		elif not re.match(r'[A-Za-z0-9]+', username):
			msg = 'Username must contain only characters and numbers!'
		elif not username or not password or not email:
			msg = 'Please fill out the form!'
		else:
			db.insert("INSERT INTO users (username,email,password) VALUES ('{0}', '{1}', '{2}')".format(username, email, password))
			# db.connection.commit()
			msg = 'You have successfully registered!'
			# cursor.close()
			return redirect(url_for('users.login'))
	elif request.method == 'POST':
		msg = 'Please fill out the form!'
	return render_template('register.html', msg=msg)
		

@users.route('/profile')
def profile():
	if 'loggedin' in session:
		# cursor = db.connection.cursor(MySQLdb.cursors.DictCursor)
		account = db.select("SELECT * FROM users WHERE idUser = '{0}'".format(session['id']))
		# account = cursor.fetchone()
		# cursor.close()
		return render_template('profile.html', account = account)
	return redirect(url_for('users.login'))

flaskblog/templates/edit_comment.html
{% extends "layout.html" %}
{% block title %}Edit Comment{% endblock %}
{% block content %}
    <h2>Edit Comment</h2><br>
    <div class="container">

        <div class="form-group">
            <dl>
                <label class="labels">Old comment context <i class="fas fa-hand-point-down"></i></label>
                <p><input class="form-control" name="context-message" type="text" value = "{{ data['context'] }}" required></p>
                <input type="hidden" name="idComment" value="{{ data['idComment'] }}">
                <label class="labels">New comment context <i class="fas fa-hand-point-down"></i></label>
                <textarea class="form-control" id="inputEditComment" name="context" rows="5"></textarea>
                <strong><div class="text-danger text-small text-center editComment-message-holder"></div></strong>
            </dl>
            <p><button class="btn-sm btn-primary" onclick="javascript:editComments();">Press to edit</button></p>
        </div>
        <div class="editCommentMessage text-sm text-danger text-center alert-danger"></div>

    </div>    

    <script>

        function editComments(){
			let editComment = document.querySelector("#inputEditComment");
			let editCommentHolder = document.querySelector(".editCommentMessage");
			let editCommentError = document.querySelector( ".editComment-message-holder" );
			let idComment = document.querySelector('input[name="idComment"]').value;
			let commentContext = document.querySelector('input[name="context-message"]').value;
            
            
			if ( idComment ) {
                
				let promise = new Promise( function( resolve, reject ) {
						// set the server request
						var xhttp = new XMLHttpRequest();
                        xhttp.onreadystatechange = function() {
                            if ( this.readyState == 4 && this.status == 200 ) {
                                // convert the response from base64 and json to obj
                                let response = JSON.parse( atob( this.responseText ) );
                                // return the server error 
                                console.log("RESPONSE::", response )
                                if( response['error'] > 0 ){
                                    reject( { 'error':2, 'errors':response } );
                                    return false;
                                }
                                resolve( response );
                            }
                        };
                        
						xhttp.open( 'POST', `${base_url}posts-ajax/edit/${idComment}`, true );
						xhttp.send(JSON.stringify( { 'context':editComment.value, 'idComment':idComment } ));
					} );
					
                    
					promise.then( ( data ) => {
						// set the response to holder
						let editCommentHolder = document.querySelector( '.editCommentMessage' );
							if ( editCommentHolder ) {
								editCommentHolder.innerHTML = data.message;
							}
						setTimeout( ()=> {
                            let params = (new URL(document.location)).searchParams;
                            let pageNumber = params.get("page");
							if (params.get("page") == "posts") {
								window.location.href = `/posts`;
							} else {
								window.location.href = `/posts/page/${pageNumber}`;
							}
						}, 500 );
					} ).catch( ( error ) => {
						let editCommentHolder = document.querySelector( '.editCommentMessage' );
						if ( editCommentHolder ) {
							// check general error
							if ( error['errors']['errors'] ) {
								editCommentHolder.innerHTML = `Eroare: ${error['error']} <br> Erori: ${error['errors']['errors']}`;
								return false;
							}
							// check validation errors
							if ( error['errors']['fields'] ) {
								// go through all errors
								for ( const item in error['errors']['fields'] ) {
									// set current value
									let value = error['errors']['fields'][item];

									if ( item == 'context' ) {
										editCommentError.innerHTML = value;
									}
									if ( item == 'idComment' ) {
										editCommentHolder.innerHTML = value;
									}
								}
							}

						}
					} );
			}

		}
    </script>
{% endblock %}
       

flaskblog/templates/home.html
{% extends 'layout.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<h2>Home Page</h2>
<p class="intro">Welcome, {{ username }} !</p>
    <div class="containers">
        <p>Would you like to make a POST ?</p>
        <br>
        <form action="/home" method="post">
            <input type="hidden" name="idUser" value="{{ idUser }}">
            <label for="title">Title</label><br>
            <div class="msg text-danger">{{ errors['title'] }}</div>
            <p><input class="form-control" type="text" name="title" value = "{{ form['title'] }}"></p><br>
            <label for="content">Content</label><br>
            <div class="msg text-danger">{{ errors['content'] }}</div>
            <input class="form-control" type="text" name ="content" value = "{{ form['content'] }}"></input><br>
            <input type="submit" class="btn btn-primary btn-sm" value="Submit the post">
        </form>
    </div>
{% endblock %}
            
            

flaskblog/templates/index.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Login</title>
		<link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css">
	</head>
	<body>
		<div class="login">
			<h1>Login</h1>
			<div class="links">
				<a href="{{ url_for('users.login') }}" class="active">Login</a>
				<a href="{{ url_for('users.register') }}">Register</a>
			</div>
			<form action="{{ url_for('users.login') }}" method="POST">
				<label for="username">
					<i class="fas fa-user"></i>
				</label>
				<input type="text" name="username" placeholder="Username" id="username" required>
				<label for="password">
					<i class="fas fa-lock"></i>
				</label>
				<input type="password" name="password" placeholder="Password" id="password" required>
				<div class="msg">{{ msg }}</div>
				<input type="submit" value="Login">
			</form>
		</div>
	</body>
</html>

flaskblog/templates/layout.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>{% block title %}{% endblock %}</title>
		<link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	</head>
	<body class="loggedin">
		<nav class="navtop sticky-top">
			<div>
				<h1>Blogs</h1>
				<a href="{{ url_for('main.home') }}"><i class="fas fa-home"></i>Home</a>
				<a href="{{ url_for('postings.posts') }}"><i class="fas fa-file"></i>Posts</a>
				<a href="{{ url_for('users.profile') }}"><i class="fas fa-user-circle"></i>Profile</a>
				<a href="{{ url_for('users.logout') }}"><i class="fas fa-sign-out-alt"></i>Logout</a>
			</div>
		</nav>
		<div class = "container">
			<div class = "content">	
				{% block content %}
				{% endblock %}
			</div>
		</div>
		<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
		<script>

			var base_url = '{{ request.url_root }}';
			// console.log(base_url);
			function myFunction(x) {
				x.classList.toggle("fa-thumbs-down");
			}
		</script>
	</body>
</html>

flaskblog/templates/profile.html
{% extends 'layout.html' %}

{% block title %}Profile{% endblock %}

{% block content %}
<h2>Profile Page</h2>
<div>
    <p>Your account details are below:</p>
    <table>
        <tr>
            <td>Username:</td>
            <td>{{ account['username'] }}</td>
        </tr>
        <tr>
            <td>Password:</td>
            <td>{{ account['password'] }}</td>
        </tr>
        <tr>
            <td>Email:</td>
            <td>{{ account['email'] }}</td>
        </tr>
    </table>
</div>
{% endblock %}

flaskblog/templates/register.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Register</title>
		<link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css">
	</head>
	<body>
		<div class="register">
			<h1>Register</h1>
			<div class="links">
				<a href="{{ url_for('users.login') }}">Login</a>
				<a href="{{ url_for('users.register') }}" class="active">Register</a>
			</div>
			<form action="{{ url_for('users.register') }}" method="POST" autocomplete="off">
				<label for="username">
					<i class="fas fa-user"></i>
				</label>
				<input type="text" name="username" placeholder="Username" id="username" required>
				<label for="password">
					<i class="fas fa-lock"></i>
				</label>
				<input type="password" name="password" placeholder="Password" id="password" required>
				<label for="email">
					<i class="fas fa-envelope"></i>
				</label>
				<input type="email" name="email" placeholder="Email" id="email" required>
				<div class="msg">{{ msg }}</div>
				<input type="submit" value="Register">
			</form>
		</div>
	</body>
</html>

flaskblog/templates/update.html
{% extends "layout.html" %}
{% block title %}Update Post{% endblock %}
{% block content %}
    <h2>Update Post</h2><br>
    <div class="container">
        <form method="POST" action="/update/{{ post['idPost'] }}">
            <dl>
            <label class="labels">Update the title <i class="fas fa-hand-point-down"></i></label>
            <strong><div class="msg text-danger">{{ errors['title'] }}</div></strong>
            <p><input class="form-control" name="title" type="text" value = "{{ post.title }}" ></p>
            <label class="labels">Update the content <i class="fas fa-hand-point-down"></i></label>
            <strong><div class="msg text-danger">{{ errors['content'] }}</div></strong>
            <p><input class="form-control" name="content" type="text" value = "{{ post.content }}" ></p>
            </dl>
            <p>
            <input type="submit" class="btn btn-primary btn-sm" value="Press to UPDATE">
            </p>
        </form>
    </div>    
{% endblock %}